### ISSUE TITLE
Too many Receivers

### ISSUE THREAD

**Issue by gokulrajats** [freshworks/freshchat-android#108]
Fatal Exception: java.lang.RuntimeException: Unable to resume activity 
com.demo.android/com.freshchat.consumer.sdk.activity.ConversationDetailActivity}: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 21670, callerPackage: com.test.android

**Comment by MuthuFD** [comment]
@gokulrajats 
1. Can you share us the full logs for this issue?
2. Can we know the Freshchat SDK version where this is happening?
3. Are you able reproduce this issue in the sample app available in this repo?

**Comment by gokulrajats** [comment]
```
com.demo.android
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4430)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

The Version is 3.6.4

**Comment by MuthuFD** [comment]
@gokulrajats 
1. Can you check logs again and share? This log does not contain Freshchat package file references
2. We are not able to reproduce this. We have very limited set of broadcast receiver. Can check this scenario in FreshchatSample in this repo? If you are able to reproduce, please share here.

**Comment by gokulrajats** [comment]
Both are comment's logs are combined as the first comment mentions the freshchat consumer activity. These are the final logs i could possibly get . Can you help me with, what could possibly rise this error, like too many receivers?

**Comment by MuthuFD** [comment]
@gokulrajats We are not able to reproduce this. We have very limited set of broadcast receiver in Freshchat SDK. 
Can you check this scenario in FreshchatSample in this repo? If you are able to reproduce, please share here.
