### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by JenyChen** [freshworks/freshchat-android#124]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 2341936 free bytes and 2MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
	at com.freshchat.consumer.sdk.i.a.doInBackground(Unknown Source)
	at com.freshchat.consumer.sdk.i.a.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by JenyChen** [comment]
init at application like: Freshchat.getInstance(getApplicationContext()).init(config);

**Comment by rameshfreshworks** [comment]
@JenyChen , Can you please provide the following details.

1. Freshchat SDK version being used? 
2. Steps to reproduce this issue? 
3. Is this happening consistently?
4. Are you using any custom implementation of image loader for Freshchat?

**Comment by JenyChen** [comment]
1. Freshchat SDK version：3.2.1
2. I down know where it is happened, maybe open?
3. Customer phone happened
4. default image loader

**Comment by rameshfreshworks** [comment]
Hi @JenyChen, We have made few image loading optimizations after 3.2.1. Would recommend updating the Freshchat SDK to the latest version 4.2.0.  
Closing this issue for now. Feel free to reopen, if you face the same issue again.

**Comment by JenyChen** [comment]
ok
