### ISSUE TITLE
Crash while parsing JSON for FAQ with enabled Proguard

### ISSUE THREAD

**Issue by kuba91** [freshworks/freshchat-android#130]
## Describe the bug
When opening FAQ in app it shows endless progress bar and crashes on parsing JSON

## Steps to reproduce
```    
* Step 1 - Enable categories for FAQ on web.
* Step 2 - Run Freshchat.showFAQs(applicationContext)
```

## Expected behavior
Showed FAQ content

## Platform
- [ ]  Android

## Freshchat SDK version
- SDK version : 4.3.3

## Device information

```
- Emulator with Android 8.1 x86
- Samsung S8+ With Android 9
- Some Xiaomi (sorry don't know what model that was)
```

## Crash log
2021-03-23 07:07:09.925 31573-31966/? E/FRESHCHAT: Exception occured
    org.json.JSONException: JSONObject["categoryId"] not a string.
        at org.json.b.i(JSONObject.java:4)
        at com.freshchat.consumer.sdk.beans.Category.getCategory(Unknown Source:7)
        at com.freshchat.consumer.sdk.service.d.e.c(Unknown Source:60)
        at com.freshchat.consumer.sdk.service.d.e.x(Unknown Source:58)
        at com.freshchat.consumer.sdk.service.c.h.a(Unknown Source:10)
        at com.freshchat.consumer.sdk.service.c.h.b(Unknown Source:2)
        at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source:45)
        at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source:90)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

## Screenshot/ Video recording 
![image](https://user-images.githubusercontent.com/6236130/112102120-12234500-8ba8-11eb-8d9a-3804de3ae95f.png)

## Additional context
Bug seems to be happen only when proguard is enabled

**Comment by rameshfreshworks** [comment]
Hi @kuba91 , is this only happening on specific devices mentioned or reproducible across all devices?

**Comment by kuba91** [comment]
I tested it only on mentioned devices but as fix i found that i was needed to add:

-keep class org.json.** { *; }

to my proguard file
