### ISSUE TITLE
Error on app launch - com.google.gson.JsonSyntaxException

### ISSUE THREAD

**Issue by amsmokefree** [freshworks/freshchat-android#131]
## Describe the bug
Error spotted on app launch, log below

## Steps to reproduce
```    
* Step 1 - Launch App
* Step 2 - Silent crash log spotted 
```

## Platform
- [ ] Android

## Freshchat SDK version
- SDK version :  4.2.0

## Device information
- [ ] is reproducible on all devices? - Yes

```
Provide device details here like
 * Device name - Google Pixel 3A
 * OS version - Android 11

```

## Crash log
if applicable, add logs here to help us debug the problem

Exception on Google Pixel 3a Android API 11 (30) >>>>> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at com.freshchat.consumer.sdk.j.ab.fromJson(Unknown Source:2)
        at com.freshchat.consumer.sdk.e.a.a(Unknown Source:7)
        at com.freshchat.consumer.sdk.e.a.cX(Unknown Source:25)
        at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source:15)
        at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source:2)
        at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source:47)
        at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source:92)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        at com.google.gson.Gson.fromJson(Gson.java:932) 
        at com.google.gson.Gson.fromJson(Gson.java:897) 
        at com.google.gson.Gson.fromJson(Gson.java:846) 
        at com.google.gson.Gson.fromJson(Gson.java:817) 
        at com.freshchat.consumer.sdk.j.ab.fromJson(Unknown Source:2) 
        at com.freshchat.consumer.sdk.e.a.a(Unknown Source:7) 
        at com.freshchat.consumer.sdk.e.a.cX(Unknown Source:25) 
        at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source:15) 
        at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source:2) 
        at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source:47) 
        at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source:92) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 

2021-03-27 16:15:51.615 18516-18665/FRESHCHAT_SERVICE: Now Processing b
2021-03-27 16:15:51.615 18516-18665/FRESHCHAT_SERVICE: Now Processing f
2021-03-27 16:15:51.615 18516-18665/FRESHCHAT_SERVICE: Now Processing a

## Screenshot/ Video recording 
If applicable, add screenshots/video recording to help explain your problem.

**Comment by rameshfreshworks** [comment]
Hi @amsmokefree 
This crash is a known case and is expected. It does not hamper Freshchat functionality in anyway.
You can ignore this crash.
