### ISSUE TITLE
React Native - Crash on triggering Freshchat.resetUser

### ISSUE THREAD

**Issue by winardis** [freshworks/freshchat-android#98]
Hi just recently experienced a crash when a user tried to logout, within the logout process i did call Freshchat.resetUser to remove the current logged in user. Upon triggering the function the app crashed and within Sentry logging we found this message "Can't downgrade database from version 6 to 5"
Can anyone help me on this issue please?

`android.database.sqlite.SQLiteException: Can't downgrade database from version 6 to 5
    at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:522)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:396)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
    at com.freshchat.consumer.sdk.c.b.cs
    at com.freshchat.consumer.sdk.c.d.bW
    at com.freshchat.consumer.sdk.j.aa.b
    at com.freshchat.consumer.sdk.j.aa.a
    at com.freshchat.consumer.sdk.j.aa.a
    at com.freshchat.consumer.sdk.Freshchat.resetUser
    at com.freshchat.consumer.sdk.react.RNFreshchatSdk.resetUser(RNFreshchatSdk.java:261)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:201)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)`

**Comment by rameshfreshworks** [comment]
Hi, From the log we think this would happen when you try to downgrade the SDK which would in turn try to downgrade the DB used. Let us know if this issue happened again along with RN SDK versions details.

**Comment by rameshfreshworks** [comment]
@winardis Closing this issue since there is no response. Feel free to reopen if this issue still exists.
